// <auto-generated />
namespace BolinsBlommor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class floatnullableintstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(floatnullableintstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201512081418369_float nullable int status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
